#!/bin/bash

echo "****************************"

plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '1,1,1 1,1,1 1,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 1' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell1 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '2,1,1 2,1,1 2,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 2' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell2 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '3,1,1 3,1,1 3,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 3' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell3 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '4,1,1 4,1,1 4,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 4' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell4 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '5,1,1 5,1,1 5,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 5' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell5 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '6,1,1 6,1,1 6,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 6' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell6 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '7,1,1 7,1,1 7,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 7' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell7 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '8,1,1 8,1,1 8,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 8' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell8 --output=KilloughOutput
plopm -i "Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH ClassicKillough-hystnew-output/CORE_EXAMPLEKILLOUGH Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '9,1,1 9,1,1 9,1,1' -c "g,y,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Killough-hysteresis  Killough hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 9' -yformat .2f -xlnum 7 -tunits h -save=curvekilloughcell9 --output=KilloughOutput




plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '1,1,1 1,1,1 1,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 1' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell1 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '2,1,1 2,1,1 2,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 2' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell2 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '3,1,1 3,1,1 3,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 3' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell3 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '4,1,1 4,1,1 4,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 4' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell4 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '5,1,1 5,1,1 5,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 5' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell5 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '6,1,1 6,1,1 6,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 6' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell6 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '7,1,1 7,1,1 7,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 7' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell7 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '8,1,1 8,1,1 8,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 8' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell8 --output=CarlsonOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON ClassicCarlson-hystnew-output/CORE_EXAMPLECARLSON Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '9,1,1 9,1,1 9,1,1' -c "b,c,k" -lw "1.5,1.5,1.5" -e "solid,dashed,dotted" -labels 'ML-Carlson-hysteresis  Carlson hysteresis  No-hysteresis' -ylabel 'Saturation at the sensor location cell 9' -yformat .2f -xlnum 7 -tunits h -save=curvecarlsoncell9 --output=CarlsonOutput



 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '2,1,1 2,1,1 2,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 1' -yformat .2f -xlnum 7 -tunits hours -save=curvelslbmcell1 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '2,1,1 2,1,1 2,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 2' -yformat .2f -xlnum 7 -tunits hours -save=curvelslbmcell2 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '3,1,1 3,1,1 3,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 3' -yformat .2f -xlnum 7 -tunits hours -save=curvelslbmcell3 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '4,1,1 4,1,1 4,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 4' -yformat .2f -xlnum 7 -tunits hours -save=curvelslbmcell4 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '5,1,1 5,1,1 5,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 5' -yformat .2f -xlnum 7 -tunits hours -save=curvelslbmcell5 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '6,1,1 6,1,1 6,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 6' -yformat .2f -xlnum 7 -tunits hours -save=curvelslbmcell6 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '7,1,1 7,1,1 7,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 7' -yformat .2f -xlnum 7 -tunits dates -save=curvelslbmcell7 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '8,1,1 8,1,1 8,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 8' -yformat .2f -xlnum 7 -tunits dates -save=curvelslbmcell8 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE" --variable "swat * 0 + 1 - swat" -s '9,1,1 9,1,1 9,1,1' -c "b,g,r" -lw "1.5,1.5,1.5" -e "solid,solid,solid" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM' -ylabel 'Saturation at the sensor location cell 9' -yformat .2f -xlnum 7 -tunits dates -save=curvelslbmcell9 --output=LSLBMOutput


 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '1,1,1 1,1,1 1,1,1 1,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 1' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell1 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '2,1,1 2,1,1 2,1,1 2,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 2' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell2 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '3,1,1 3,1,1 3,1,1 3,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 3' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell3 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '4,1,1 4,1,1 4,1,1 4,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 4' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell4 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '5,1,1 5,1,1 5,1,1 5,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 5' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell5 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '6,1,1 6,1,1 6,1,1 6,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 6' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell6 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '7,1,1 7,1,1 7,1,1 7,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 7' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell7 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '8,1,1 8,1,1 8,1,1 8,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 8' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell8 --output=LSLBMOutput
 plopm -i "Carlsonmlhystnew-output/CORE_EXAMPLECARLSON Killoughmlhystnew-output/CORE_EXAMPLEKILLOUGH LSLBMmlhystnew-output/CORE_EXAMPLE Nohysteresis-output/CORE_EXAMPLENOHYST" --variable "swat * 0 + 1 - swat" -s '9,1,1 9,1,1 9,1,1 9,1,1' -c "b,g,r,k" -lw "1.5,1.5,1.5,1.5" -e "solid,solid,solid,dotted" -labels 'ML-Carlson-hysteresis  ML-Killough-hysteresis  ML-LS-LBM  No-hysteresis' -ylabel 'Saturation at the sensor location cell 9' -yformat .2f -xlnum 7 -tunits h -save=lslbmcell9 --output=LSLBMOutput




 echo "ALL NUMERICAL TESTS COMPUTED "


 # /Users/macbookn/activopmwkspc/edgedev/build/opm-simulators/bin/flow --activate-m-l-rel-p-erm=True    --newton-max-iterations=20 --relaxed-max-pv-fraction=0 --output-extra-convergence-info=steps,iterations --enable-opm-rst-file=true --newton-min-iterations=1 --enable-well-operability-check=false --min-time-step-before-shutting-problematic-wells-in-days=1e-99 --output-dir=killoughmlhystnew-output CORE_ExampleKillough.DATA
# /Users/macbookn/activopmwkspc/edgedev/build/opm-simulators/bin/flow --activate-m-l-rel-p-erm=True    --newton-max-iterations=20 --relaxed-max-pv-fraction=0 --output-extra-convergence-info=steps,iterations --enable-opm-rst-file=true --newton-min-iterations=1 --enable-well-operability-check=false --min-time-step-before-shutting-problematic-wells-in-days=1e-99 --output-dir=Carlsonmlhystnew-output CORE_ExampleCarlson.DATA

 #/Users/macbookn/activopmwkspc/edgedev/build/opm-simulators/bin/flow  --newton-max-iterations=20 --relaxed-max-pv-fraction=0 --output-extra-convergence-info=steps,iterations --enable-opm-rst-file=true --newton-min-iterations=1 --enable-well-operability-check=false --min-time-step-before-shutting-problematic-wells-in-days=1e-99 --output-dir=ClassicKillough-hystnew-output CORE_ExampleKillough.DATA

 #/Users/macbookn/activopmwkspc/edgedev/build/opm-simulators/bin/flow  --newton-max-iterations=20 --relaxed-max-pv-fraction=0 --output-extra-convergence-info=steps,iterations --enable-opm-rst-file=true --newton-min-iterations=1 --enable-well-operability-check=false --min-time-step-before-shutting-problematic-wells-in-days=1e-99 --output-dir=ClassicCarlson-hystnew-output CORE_ExampleCarlson.DATA

 #/Users/macbookn/activopmwkspc/edgedev/build/opm-simulators/bin/flow  --newton-max-iterations=20 --relaxed-max-pv-fraction=0 --output-extra-convergence-info=steps,iterations --enable-opm-rst-file=true --newton-min-iterations=1 --enable-well-operability-check=false --min-time-step-before-shutting-problematic-wells-in-days=1e-99 --output-dir=Nohysteresis-output CORE_Examplenohyst.DATA

 #/Users/macbookn/activopmwkspc/edgedev/build/opm-simulators/bin/flow --activate-m-l-rel-p-erm=True    --newton-max-iterations=20 --relaxed-max-pv-fraction=0 --output-extra-convergence-info=steps,iterations --enable-opm-rst-file=true --newton-min-iterations=1 --enable-well-operability-check=false --min-time-step-before-shutting-problematic-wells-in-days=1e-99 --output-dir=LSLBMmlhystnew-output CORE_Example.DATA
